# Generated by Django 5.1.7 on 2025-04-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=201)),
                ('content', models.TextField()),
                ('create_ta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
