# Generated by Django 5.1.7 on 2025-04-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fleet', '0002_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_ta',
            new_name='create_at',
        ),
    ]
