# Generated by Django 5.2.1 on 2025-05-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fleet', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='end_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='start_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='travel_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
