# Generated by Django 5.2.1 on 2025-05-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fleet', '0006_post_distance_post_end_location_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
