# Generated by Django 5.2.1 on 2025-05-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fleet', '0007_remove_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_at',
            new_name='create_at',
        ),
    ]
