# Generated by Django 5.2.1 on 2025-05-20 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fleet', '0008_rename_create_at_post_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Autor posta (odniesienie do modelu User)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Treść posta'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data i czas utworzenia posta (ustawiane automatycznie)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='distance',
            field=models.FloatField(blank=True, help_text='Dystans (np. w kilometrach); pole opcjonalne', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='end_location',
            field=models.CharField(blank=True, help_text='Punkt końcowy podróży; pole opcjonalne', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_location',
            field=models.CharField(blank=True, help_text='Punkt początkowy podróży; pole opcjonalne', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Tytuł posta (maks. 200 znaków)', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='travel_time',
            field=models.DurationField(blank=True, help_text='Czas podróży; pole opcjonalne', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='vehicle',
            field=models.CharField(blank=True, help_text='Informacja o pojeździe; pole opcjonalne', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data i czas utworzenia zadania (ustawiane automatycznie)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Opis zadania; pole opcjonalne', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Tytuł zadania (maks. 200 znaków)', max_length=200),
        ),
    ]
