# Generated by Django 5.2.1 on 2025-05-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fleet', '0009_alter_post_author_alter_post_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
